In [5]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression


In [4]:
df = pd.read_csv('/content/sample_data/homeprices.csv')
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [17]:
reg = LinearRegression()
model = reg.fit(df[['area']],df.price)

In [18]:
model.predict([[4200]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([750924.65753425])

In [19]:
model.coef_

array([135.78767123])

In [20]:
model.intercept_

180616.43835616432

Save Model To a File Using Python Pickle

In [23]:
import pickle
with open('/content/sample_data/model_pickle', 'wb') as file:
  pickle.dump(model,file)

In [35]:
#from sklearn.externals import joblib
import joblib
with open('/content/sample_data/model_joblib', 'wb') as file:
  joblib.dump(model,file)

<h4 style='color:purple'>Load Saved Model</h4>

In [37]:
loaded_model = joblib.load('/content/sample_data/model_joblib','r+')

In [39]:
loaded_model.predict([[5000]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])